using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using FM_Grupo2.Models;

namespace FM_Grupo2.DAL
{
    public class FMInitializer : System.Data.Entity.DropCreateDatabaseIfModelChanges<FMContext>
    {
        protected override void Seed(FMContext context)
        {
            var scope = new List<ScopeModel>
            {
                new ScopeModel{descriptionEN="National",descriptionPT="Nacional"},
                new ScopeModel{descriptionEN="International", descriptionPT="Internacional"}
            };

            scope.ForEach(s => context.Scope.Add(s));
            context.SaveChanges();

            var frequency = new List<FrequencyModel>
            {
                new FrequencyModel{descriptionEN="Annual",descriptionPT="Anual"},
                new FrequencyModel{descriptionEN="4 in 4 years",descriptionPT="De 4 em 4 anos"}
            };

            frequency.ForEach(f => context.Frequency.Add(f));
            context.SaveChanges();

            var country = new List<CountryModel>
            {
               new CountryModel{NameEN="Afghanistan",NamePT="Afeganistão"},
               new CountryModel{NameEN=" South Africa ",NamePT="África do Sul"},
               new CountryModel{NameEN="Albania",NamePT="Albânia"},
               new CountryModel{NameEN="Germany",NamePT="Alemanha"},
               new CountryModel{NameEN="Andorra",NamePT="Andorra"},
               new CountryModel{NameEN="Angola",NamePT="Angola"},
               new CountryModel{NameEN="Antigua and Barbuda",NamePT="Antigua e Barbuda"},
               new CountryModel{NameEN="Saudi Arabia",NamePT="Arábia Saudita"},
               new CountryModel{NameEN="Algeria",NamePT="Argélia"},
               new CountryModel{NameEN="Argentina",NamePT="Argentina"},
               new CountryModel{NameEN="Armenia",NamePT="Arménia"},
               new CountryModel{NameEN="Australia",NamePT="Austrália"},
               new CountryModel{NameEN="Austria",NamePT="Áustria"},
               new CountryModel{NameEN="Azerbaijan",NamePT="Azerbeijão"},
               new CountryModel{NameEN="Bahamas",NamePT="Bahamas"},
               new CountryModel{NameEN="Bahrain",NamePT="Bahrain"},
               new CountryModel{NameEN="Bangladesh",NamePT="Bangladesh"},
               new CountryModel{NameEN="Barbados",NamePT="Barbados"},
               new CountryModel{NameEN="Belgium",NamePT="Bélgica"},
               new CountryModel{NameEN="Belize",NamePT="Belize"},
               new CountryModel{NameEN="Benin",NamePT="Benim"},
               new CountryModel{NameEN="Bermudas",NamePT="Bermudas"},
               new CountryModel{NameEN="Belarus",NamePT="Bielorússia"},
               new CountryModel{NameEN="Bolivia",NamePT="Bolívia"},
               new CountryModel{NameEN="Bosnia and Herzegovina",NamePT="Bósnia-Herzegovina"},
               new CountryModel{NameEN="Botswana",NamePT="Botswana"},
               new CountryModel{NameEN="Brazil",NamePT="Brasil"},
               new CountryModel{NameEN="Brunei",NamePT="Brunei"},
               new CountryModel{NameEN="Bulgaria",NamePT="Bulgária"},
               new CountryModel{NameEN="Burkina Faso",NamePT="Burkina Faso"},
               new CountryModel{NameEN="Burundi",NamePT="Burundi"},
               new CountryModel{NameEN="Bhutan",NamePT="Butão"},
               new CountryModel{NameEN="",NamePT="Cabo Verde"},
               new CountryModel{NameEN="",NamePT="Camarões"},
               new CountryModel{NameEN="",NamePT="Cambodja"},
               new CountryModel{NameEN="",NamePT="Canadá"},
               new CountryModel{NameEN="",NamePT="Casaquistão"},
               new CountryModel{NameEN="",NamePT="Chade"},
               new CountryModel{NameEN="",NamePT="Chile"},
               new CountryModel{NameEN="",NamePT="China"},
               new CountryModel{NameEN="",NamePT="Chipre"},
               new CountryModel{NameEN="",NamePT="Colômbia"},
               new CountryModel{NameEN="",NamePT="Comores"},
               new CountryModel{NameEN="",NamePT="Cook (Ilhas)"},
               new CountryModel{NameEN="",NamePT="Coreia do Norte"},
               new CountryModel{NameEN="",NamePT="Coreia do Sul"},
               new CountryModel{NameEN="",NamePT="Costa do Marfim"},
               new CountryModel{NameEN="",NamePT="Costa Rica"},
               new CountryModel{NameEN="",NamePT="Croácia"},
               new CountryModel{NameEN="",NamePT="Cuba"},
               new CountryModel{NameEN="",NamePT="Dinamarca"},
               new CountryModel{NameEN="",NamePT="Djibouti"},
               new CountryModel{NameEN="",NamePT="Dominica"},
               new CountryModel{NameEN="",NamePT="Egipto"},
               new CountryModel{NameEN="",NamePT="El Salvador"},
               new CountryModel{NameEN="",NamePT="Emiratos Árabes Unidos"},
               new CountryModel{NameEN="",NamePT="Equador"},
               new CountryModel{NameEN="",NamePT="Eritreia"},
               new CountryModel{NameEN="",NamePT="Eslováquia"},
               new CountryModel{NameEN="",NamePT="Eslovénia"},
               new CountryModel{NameEN="",NamePT="Espanha"},
               new CountryModel{NameEN="",NamePT="Estónia"},
               new CountryModel{NameEN="",NamePT="Etiópia"},
               new CountryModel{NameEN="",NamePT="EUA"},
               new CountryModel{NameEN="",NamePT="Fiji"},
               new CountryModel{NameEN="",NamePT="Filipinas"},
               new CountryModel{NameEN="",NamePT="Finlândia"},
               new CountryModel{NameEN="",NamePT="França"},
               new CountryModel{NameEN="",NamePT="Gabão"},
               new CountryModel{NameEN="",NamePT="Gâmbia"},
               new CountryModel{NameEN="",NamePT="Geórgia"},
               new CountryModel{NameEN="",NamePT="Ghana"},
               new CountryModel{NameEN="",NamePT="Grécia"},
               new CountryModel{NameEN="",NamePT="Grenada"},
               new CountryModel{NameEN="",NamePT="Guatemala"},
               new CountryModel{NameEN="",NamePT="Guiana"},
               new CountryModel{NameEN="",NamePT="Guiné Bissau"},
               new CountryModel{NameEN="",NamePT="Guiné Conacry"},
               new CountryModel{NameEN="",NamePT="Guiné Equatorial"},
               new CountryModel{NameEN="",NamePT="Haiti"},
               new CountryModel{NameEN="",NamePT="Honduras"},
               new CountryModel{NameEN="",NamePT="Hungria"},
               new CountryModel{NameEN="",NamePT="Iémen"},
               new CountryModel{NameEN="",NamePT="India"},
               new CountryModel{NameEN="",NamePT="Indonésia"},
               new CountryModel{NameEN="",NamePT="Irão"},
               new CountryModel{NameEN="",NamePT="Iraque"},
               new CountryModel{NameEN="",NamePT="Irlanda"},
               new CountryModel{NameEN="",NamePT="Islândia"},
               new CountryModel{NameEN="",NamePT="Israel"},
               new CountryModel{NameEN="",NamePT="Itália"},
               new CountryModel{NameEN="",NamePT="Jamaica"},
               new CountryModel{NameEN="",NamePT="Japão"},
               new CountryModel{NameEN="",NamePT="Jordânia"},
               new CountryModel{NameEN="",NamePT="Kirguistão"},
               new CountryModel{NameEN="",NamePT="Kiribati"},
               new CountryModel{NameEN="",NamePT="Koweit"},
               new CountryModel{NameEN="",NamePT="Kosovo"},
               new CountryModel{NameEN="",NamePT="Laos"},
               new CountryModel{NameEN="",NamePT="Lesoto"},
               new CountryModel{NameEN="",NamePT="Letónia"},
               new CountryModel{NameEN="",NamePT="Líbano"},
               new CountryModel{NameEN="",NamePT="Libéria"},
               new CountryModel{NameEN="",NamePT="Líbia"},
               new CountryModel{NameEN="",NamePT="Liechtenstein"},
               new CountryModel{NameEN="",NamePT="Lituânia"},
               new CountryModel{NameEN="",NamePT="Luxemburgo"},
               new CountryModel{NameEN="",NamePT="Macedónia"},
               new CountryModel{NameEN="",NamePT="Madagáscar"},
               new CountryModel{NameEN="",NamePT="Malásia"},
               new CountryModel{NameEN="",NamePT="Malawi"},
               new CountryModel{NameEN="",NamePT="Maldivas"},
               new CountryModel{NameEN="",NamePT="Mali"},
               new CountryModel{NameEN="",NamePT="Malta"},
               new CountryModel{NameEN="",NamePT="Marrocos"},
               new CountryModel{NameEN="",NamePT="Marshall (Ilhas)"},
               new CountryModel{NameEN="",NamePT="Maurícias"},
               new CountryModel{NameEN="",NamePT="Mauritânia"},
               new CountryModel{NameEN="",NamePT="México"},
               new CountryModel{NameEN="",NamePT="Micronésia"},
               new CountryModel{NameEN="",NamePT="Moçambique"},
               new CountryModel{NameEN="",NamePT="Moldova"},
               new CountryModel{NameEN="",NamePT="Mónaco"},
               new CountryModel{NameEN="",NamePT="Mongólia"},
               new CountryModel{NameEN="",NamePT="Montenegro"},
               new CountryModel{NameEN="",NamePT="Myanmar"},
               new CountryModel{NameEN="",NamePT="Namíbia"},
               new CountryModel{NameEN="",NamePT="Nauru"},
               new CountryModel{NameEN="",NamePT="Nepal"},
               new CountryModel{NameEN="",NamePT="Nicarágua"},
               new CountryModel{NameEN="",NamePT="Níger"},
               new CountryModel{NameEN="",NamePT="Nigéria"},
               new CountryModel{NameEN="",NamePT="Noruega"},
               new CountryModel{NameEN="",NamePT="Nova Zelândia"},
               new CountryModel{NameEN="",NamePT="Oman"},
               new CountryModel{NameEN="",NamePT="Países Baixos"},
               new CountryModel{NameEN="",NamePT="Palau"},
               new CountryModel{NameEN="",NamePT="Panamá"},
               new CountryModel{NameEN="",NamePT="Papua Nova Guiné"},
               new CountryModel{NameEN="",NamePT="Paquistão"},
               new CountryModel{NameEN="",NamePT="Paraguai"},
               new CountryModel{NameEN="",NamePT="Perú"},
               new CountryModel{NameEN="",NamePT="Polónia"},
               new CountryModel{NameEN="",NamePT="Porto Rico"},
               new CountryModel{NameEN="",NamePT="Portugal"},
               new CountryModel{NameEN="",NamePT="Qatar"},
               new CountryModel{NameEN="",NamePT="Quénia"},
               new CountryModel{NameEN="",NamePT="Reino Unido"},
               new CountryModel{NameEN="",NamePT="República Centro Africana"},
               new CountryModel{NameEN="",NamePT="República Checa"},
               new CountryModel{NameEN="",NamePT="República Democrática do Congo"},
               new CountryModel{NameEN="",NamePT="República do Congo"},
               new CountryModel{NameEN="",NamePT="República Dominicana"},
               new CountryModel{NameEN="",NamePT="Roménia"},
               new CountryModel{NameEN="",NamePT="Ruanda"},
               new CountryModel{NameEN="",NamePT="Rússia"},
               new CountryModel{NameEN="",NamePT="Salomão (Ilhas)"},
               new CountryModel{NameEN="",NamePT="Samoa"},
               new CountryModel{NameEN="",NamePT="Santa Lucia"},
               new CountryModel{NameEN="",NamePT="São Cristóvão e Nevis"},
               new CountryModel{NameEN="",NamePT="São Marino"},
               new CountryModel{NameEN="",NamePT="São Tomé e Príncipe"},
               new CountryModel{NameEN="",NamePT="São Vicente e Grenadinas"},
               new CountryModel{NameEN="",NamePT="Senegal"},
               new CountryModel{NameEN="",NamePT="Serra Leoa"},
               new CountryModel{NameEN="",NamePT="Sérvia"},
               new CountryModel{NameEN="",NamePT="Seychelles"},
               new CountryModel{NameEN="",NamePT="Singapura"},
               new CountryModel{NameEN="",NamePT="Síria"},
               new CountryModel{NameEN="",NamePT="Somália"},
               new CountryModel{NameEN="",NamePT="Sri Lanka"},
               new CountryModel{NameEN="",NamePT="Suazilândia"},
               new CountryModel{NameEN="",NamePT="Sudão"},
               new CountryModel{NameEN="",NamePT="Sudão do Sul"},
               new CountryModel{NameEN="",NamePT="Suécia"},
               new CountryModel{NameEN="",NamePT="Suiça"},
               new CountryModel{NameEN="",NamePT="Suriname"},
               new CountryModel{NameEN="",NamePT="Tailândia"},
               new CountryModel{NameEN="",NamePT="Tajiquistão"},
               new CountryModel{NameEN="",NamePT="Tanzânia"},
               new CountryModel{NameEN="",NamePT="Timor Leste"},
               new CountryModel{NameEN="",NamePT="Togo"},
               new CountryModel{NameEN="",NamePT="Tonga"},
               new CountryModel{NameEN="",NamePT="Trinidad e Tobago"},
               new CountryModel{NameEN="",NamePT="Tunísia"},
               new CountryModel{NameEN="",NamePT="Turquemenistão"},
               new CountryModel{NameEN="",NamePT="Turquia"},
               new CountryModel{NameEN="",NamePT="Tuvalu"},
               new CountryModel{NameEN="",NamePT="Ucrânia"},
               new CountryModel{NameEN="",NamePT="Uganda"},
               new CountryModel{NameEN="",NamePT="Uruguai"},
               new CountryModel{NameEN="",NamePT="Uzbequistão"},
               new CountryModel{NameEN="",NamePT="Vanuatu"},
               new CountryModel{NameEN="",NamePT="Venezuela"},
               new CountryModel{NameEN="",NamePT="Vietnam"},
               new CountryModel{NameEN="",NamePT="Zâmbia"},
               new CountryModel{NameEN="",NamePT="Zimbabué"},
            };

            country.ForEach(c => context.Country.Add(c));
            context.SaveChanges();
        }
    }
}